services:
  postgres:
    image: postgres:16-alpine
    container_name: milktea_postgres
    restart: always
    environment:
      POSTGRES_DB: MilkTeaDb
      POSTGRES_USER: milktea_user
      POSTGRES_PASSWORD: MilkTea@2025
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U milktea_user -d MilkTeaDb"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
    driver: local
